// client/src/components/Login.jsx
import React, { useState } from "react";
import { Link, useHistory } from "react-router-dom";
import api from "../services/api";

export default props => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(undefined);
  const history = useHistory();

  const login = event => {
    event.preventDefault();
    api
      .login(email, password)
      .then(res => history.push("/search"))
      .catch(err => setError(true));
  };

  return (
    <div className="w-full max-w-sm mx-auto py-4 mt-20 bg-white shadow-2xl">
      <form className="flex flex-col px-6" onSubmit={login}>
        <label className="pt-4 font-bold text-sm" htmlFor="email">
          email
        </label>
        <input
          className="p-2 appearance-none bg-brand-white font-bold text-lg shadow-inner"
          id="email"
          type="text"
          value={email}
          onChange={event => {
            event.preventDefault();
            setEmail(event.target.value);
          }}
        ></input>
        <label className="pt-4 font-bold text-sm" htmlFor="password">
          password
        </label>
        <input
          className="p-2 appearance-none bg-brand-white font-bold text-lg shadow-inner"
          id="password"
          type="password"
          value={password}
          onChange={event => {
            event.preventDefault();
            setPassword(event.target.value);
          }}
        ></input>
        <p className="pt-4 text-center font-bold text-sm">
          Dont have an account?{" "}
          <Link className="text-brand-blue-500" to="/signup">
            Register!
          </Link>
        </p>
        <input
          className="p-2 bg-brand-blue-500 hover:text-white font-bold text-lg shadow-md cursor-pointer"
          type="submit"
          value="login"
        ></input>
      </form>
    </div>
  );
};

// client-svelte/src/components/login.svelte
<script>
  import { replace, push, link } from "svelte-spa-router";
  import api from "../services/api";
  import { user } from "../stores/user";

  let email;
  let password;

  const login = () => {
    api
      .login(email, password)
      .then((res) => {
        user.set(res);
        replace("/search");
      })
      .catch((err) => user.set(null));
  };
</script>

<style>
  .container {
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  form {
    max-width: 360px;
    padding: 1rem 1.5rem;
  }
  label {
    font-size: 1rem;
    display: block;
  }
  input.field {
    margin-bottom: 0.7rem;
  }
  input.login {
    margin-top: 1.5rem;
  }
  input {
    display: block;
    width: 100%;
  }
  a {
    display: block;
    margin: auto;
    text-align: center;
  }
</style>

<div class="container">
  <form on:submit|preventDefault={login}>
    <label for="email">email</label>
    <input class="field" id="email" type="text" bind:value={email} />
    <label for="password">password</label>
    <input class="field" id="password" type="password" bind:value={password} />
    <input class="login" type="submit" value="login" />
    <a href="/signup" use:link>create a new account</a>
  </form>
</div>
