// client/src/components/SignUp.jsx
import React, { useState } from "react";
import { useHistory } from "react-router-dom";
import api from "../services/api";

export default props => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(undefined);
  const history = useHistory();

  const signup = event => {
    event.preventDefault();
    api
      .signup(email, password)
      .then(() => history.push("/login"))
      .catch(err => setError(true));
  };

  return (
    <div>
      <span>sign up</span>
      <form onSubmit={signup}>
        <input
          type="email"
          value={email}
          onChange={event => {
            event.preventDefault();
            setEmail(event.target.value);
          }}
        ></input>
        <input
          type="password"
          value={password}
          onChange={event => {
            event.preventDefault();
            setPassword(event.target.value);
          }}
        ></input>
        <input type="submit"></input>
      </form>
    </div>
  );
};

// client-svelte/src/components/signup.svelte
<script>
  import { replace } from "svelte-spa-router";
  import api from "../services/api";
  import { user } from "../stores/user";

  let email;
  let password;

  const signup = () => {
    api
      .signup(email, password)
      .then((res) => {
        user.set(res);
        replace("/search");
      })
      .catch((err) => user.set(null));
  };
</script>

<style>
  form {
    width: 50%;
  }
  label {
    font-size: medium;
    display: block;
  }
  input {
    display: block;
    width: 100%;
    margin-bottom: 1rem;
  }
</style>

<form on:submit|preventDefault={signup}>
  <label for="email">email</label>
  <input id="email" type="text" bind:value={email} />
  <label for="password">password</label>
  <input id="password" type="password" bind:value={password} />
  <input type="submit" value="sign up" />
</form>
