// client-svelte/src/components/hidden.svelte
<script>
  import { onMount } from "svelte";
  import Nav from "./nav.svelte";
  import { replace } from "svelte-spa-router";
  import Results from "./results.svelte";
  import { vacancies } from "../stores/vacancies";

  onMount(() => vacancies.hidden().catch((err) => replace("/login")));
</script>

<Nav />

<Results />

// client/src/components/Hidden.jsx
import React, { useState, useEffect } from "react";
import { useHistory } from "react-router-dom";
import api from "../services/api";
import Results from "./Results";

export default props => {
  const [vacancies, setVacancies] = useState([]);
  const history = useHistory();

  useEffect(() => {
    api
      .getHidden()
      .then(res => {
        setVacancies(res);
      })
      .catch(err => history.push("/login"));
  }, [history]);

  const onChange = () => {
    api
      .getHidden()
      .then(res => {
        setVacancies(res);
      })
      .catch(err => history.push("/login"));
  };

  return (
    <div className="my-10">
      <div className="mt-2 shadow-xl">
        <Results vacancies={vacancies} onChange={onChange}></Results>
      </div>
    </div>
  );
};
